TimeTable/Models/Lesson.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;

namespace TimeTable.Models {
    public class Lesson {
        public int Id { get; set; }
        [DisplayName("id дисциплины")]
        public int Discipline { get; set; }
        [DisplayName("id группы")]
        public int Group { get; set; }
        [DisplayName("Преподаватель")]
        public int Teacher { get; set; }

        [DisplayName("Дисциплина")]
        public string DisciplineText { get; set; }
        [DisplayName("Группа")]
        public string GroupText { get; set; }
        [DisplayName("Преподаватель")]
        public string TeacherText { get; set; }
    }
}

TimeTable/Controllers/DisciplineController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TimeTable.DAO;
using TimeTable.Models;

namespace TimeTable.Controllers {
    public class DisciplineController : Controller {
        DAODiscipline daoDiscipline = new DAODiscipline();
        DAOLesson daoLesson = new DAOLesson();

        // GET: Discipline
        [Authorize(Roles = "Спец. по кадрам, Преподаватель")]
        public ActionResult Index() {
            return View(DAODiscipline.GetDisciplines());
        }

        [Authorize(Roles = "Спец. по кадрам")]
        public ActionResult Create() {
            ViewBag.Message = DAOUser.GetTeachers();
            return View(new Discipline());
        }

        [HttpPost]
        public ActionResult Create([Bind(Exclude = "Id")] Discipline dd) {
            try {
                if (daoDiscipline.InsertDiscipline(dd))
                    return RedirectToAction("Index");
                else
                    return RedirectToAction("Index");
            } catch (Exception ex){
                Logger.Logger.Log.Info("Неудалось добавить дисциплину: " + ex);
                return RedirectToAction("Index");
            }
        }

        [Authorize(Roles = "Спец. по кадрам, Преподаватель")]
        public ActionResult Details(int id) {
            return View(DAODiscipline.GetDiscipline(id));
        }

        [Authorize(Roles = "Спец. по кадрам")]
        public ActionResult Delete(int id) {
            return View(DAODiscipline.GetDiscipline(id));
        }

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection) {
            if (ModelState.IsValid && DAODiscipline.DeleteDiscipline(id))
                return RedirectToAction("Index");
            return View();
        }

        [Authorize(Roles = "Спец. по кадрам")]
        public ActionResult Edit(int id) {
            ViewBag.Message = DAOUser.GetTeachers();
            return View(DAODiscipline.GetDiscipline(id));
        }

        // POST: Home/Edit/5
        [HttpPost]
        public ActionResult Edit([Bind(Include = "Id, Name, User, UserText")]Discipline discipline) {
            if (ModelState.IsValid && DAODiscipline.EditDiscipline(discipline))
                return RedirectToAction("Index");
            return View();
        }
    }
}

TimeTable/Controllers/LessonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TimeTable.DAO;
using TimeTable.Models;

namespace TimeTable.Controllers {
    public class LessonController : Controller {
        DAOLesson daoLesson = new DAOLesson();

        // GET: Lesson
        [Authorize(Roles = "Спец. по кадрам, Преподаватель")]
        public ActionResult Index() {
            return View(daoLesson.GetLessonContainer());
        }

        public ActionResult Disc() {
            return View(DAODiscipline.GetDisciplines());
        }

        public ActionResult Year() {
            return View(DAOGroup.GetGroups());
        }

        [Authorize(Roles = "Спец. по кадрам")]
        public ActionResult Create() {
            ViewBag.Message = daoLesson.GetLessonContainer();
            return View(new Lesson());
        }

        [HttpPost]
        public ActionResult Create([Bind(Exclude = "Id")] Lesson dl) {
            try {
                if (daoLesson.InsertLesson(dl))
                    return RedirectToAction("Index");
                else
                    return RedirectToAction("Index");
            } catch(Exception ex) {
                Logger.Logger.Log.Info("Не удалось создать заполнить клетку расписания: " + ex);
                return RedirectToAction("Index");
            }
        }

        [Authorize(Roles = "Спец. по кадрам, Преподаватель")]
        public ActionResult Details(int id) {
            return View(DAOLesson.GetLesson(id));
        }

        [Authorize(Roles = "Спец. по кадрам")]
        public ActionResult Delete(int id) {
            return View(DAOLesson.GetLesson(id));
        }

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection) {
            if (ModelState.IsValid && DAOLesson.DeleteLesson(id))
                return RedirectToAction("Index");
            return View();
        }

        // GET: Home/Edit/5
        [Authorize(Roles = "Спец. по кадрам")]
        public ActionResult Edit(int id) {
            ViewBag.Message = daoLesson.GetLessonContainer();
            return View(DAOLesson.GetLesson(id));
        }

        // POST: Home/Edit/5
        [HttpPost]
        public ActionResult Edit([Bind(Include = "Id, Discipline, Group, Teacher")]Lesson lesson) {
            if (ModelState.IsValid && DAOLesson.EditLesson(lesson))
                return RedirectToAction("Index");
            return View();
        }

    }
}

TimeTable/Views/Lesson/Create.cshtml
@model TimeTable.Models.Lesson

@{
    ViewBag.Title = "Создание";
}

<h2>Создание</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ActionLink("Создать дисциплину", "Create", "Discipline", null, new { @class = "btn m-1" })
    <div class="form-horizontal">
        <h4>Занятие</h4>

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <p class="control-label col-md-2"><b>Дисциплина</b></p>
            <div class="col-md-10">
                <select name="Discipline" class="form-control">
                    <option value="-1" selected>Выберите ...</option>
                    @foreach (var item in ((LessionContainer)ViewBag.Message).GetDisciplines()) {
                        <option value="@Html.DisplayFor(modelItem => item.Id)">
                            @Html.DisplayFor(modelItem => item.Name)
                        </option>
                    }
                </select>
                @Html.ValidationMessageFor(model => model.Discipline, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <p class="control-label col-md-2"><b>Группы</b></p>
            <div class="col-md-10">
                <select name="Group" class="form-control">
                    <option value="-1" selected>Выберите ...</option>
                    @foreach (var item in ((LessionContainer)ViewBag.Message).GetGroups()) {
                        <option value="@Html.DisplayFor(modelItem => item.Id)">
                            @Html.DisplayFor(modelItem => item.Name)@Html.DisplayFor(modelItem => item.Year)
                        </option>
                    }
                </select>
                @Html.ValidationMessageFor(model => model.Group, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Teacher, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">

                <select name="Teacher" class="form-control">
                    <option value="-1" selected>Выберите ...</option>
                    @foreach (var item in ((LessionContainer)ViewBag.Message).GetUsers()) {
                        <option value="@Html.DisplayFor(modelItem => item.Id)">
                            @Html.DisplayFor(modelItem => item.Name)
                        </option>
                    }
                </select>
                @Html.ValidationMessageFor(model => model.Teacher, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Создать" class="btn btn-default" />
            </div>
        </div>
    </div>

}

TimeTable/Views/Lesson/Delete.cshtml
@model TimeTable.Models.Lesson

@{
    ViewBag.Title = "Удаление";
}

<h2>Удаление</h2>

<h3>Вы действительно хотите удалить это занятие?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.DisciplineText)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DisciplineText)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GroupText)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GroupText)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TeacherText)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TeacherText)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Удалить" class="btn btn-default" /> |
            @Html.ActionLink("< Вернуться к списку занятий", "Index")
        </div>
    }
</div>

TimeTable/Views/Lesson/Details.cshtml
@model TimeTable.Models.Lesson

@{
    ViewBag.Title = "Детали";
}

<h2>Детали</h2>

<div>
    <h4>Занятие</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Discipline)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Discipline)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Group)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Group)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Teacher)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Teacher)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DisciplineText)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DisciplineText)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GroupText)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GroupText)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TeacherText)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TeacherText)
        </dd>

    </dl>
</div>
<p>
    @*@Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |*@
    @Html.ActionLink("< Вернуться к списку занятий", "Index")
</p>

TimeTable/Views/Lesson/Edit.cshtml
@model TimeTable.Models.Lesson

@{
    ViewBag.Title = "Редактировать";
}

<h2>Редактирование</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Занятие</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)


    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        <p class="control-label col-md-2"><b>Дисциплина</b></p>
        <div class="col-md-10">
            <select name="Discipline" class="form-control">
                <option value="-1" selected> @Html.DisplayFor(model => model.DisciplineText)</option>
                @foreach (var item in ((LessionContainer)ViewBag.Message).GetDisciplines()) {
                    <option value="@Html.DisplayFor(modelItem => item.Id)">
                        @Html.DisplayFor(modelItem => item.Name)
                    </option>
                }
            </select>
            @Html.ValidationMessageFor(model => model.Discipline, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <p class="control-label col-md-2"><b>Группы</b></p>
        <div class="col-md-10">
            <select name="Group" class="form-control">
                <option value="-1" selected> @Html.DisplayFor(model => model.GroupText)</option>
                @foreach (var item in ((LessionContainer)ViewBag.Message).GetGroups()) {
                    <option value="@Html.DisplayFor(modelItem => item.Id)">
                        @Html.DisplayFor(modelItem => item.Name)@Html.DisplayFor(modelItem => item.Year)
                    </option>
                }
            </select>
            @Html.ValidationMessageFor(model => model.Group, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Teacher, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">

            <select name="Teacher" class="form-control">
                <option value="-1" selected>@Html.DisplayFor(model => model.TeacherText)</option>
                @foreach (var item in ((LessionContainer)ViewBag.Message).GetUsers()) {
                    <option value="@Html.DisplayFor(modelItem => item.Id)">
                        @Html.DisplayFor(modelItem => item.Name)
                    </option>
                }
            </select>
            @Html.ValidationMessageFor(model => model.Teacher, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Сохранить" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("< Вернуться к списку", "Index")
</div>

TimeTable/Views/Lesson/Index.cshtml
@model LessionContainer

@{
    ViewBag.Title = "Lesson";
}

<div class="editbar">
    <div class="left">
        <h2>Занятие</h2>
    </div>
    <div class="right">
        @Html.ActionLink("Создать", "Create", null, new { @class = "btn m-1" })
    </div>
</div>


<table class="table">
    <tr>
        <th>
            @Html.ActionLink("Дисциплина", "Index", "Discipline")
        </th>
        <th>
            @Html.ActionLink("Группы", "Index", "Group")
        </th>
        <th>
            @Html.DisplayNameFor(model => Model.GetLessons()[0].Teacher)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model.GetLessons()) {
        <tr data-id="@Html.DisplayFor(modelItem => item.Id)">
            <td data-id="@Html.DisplayFor(modelItem => item.Discipline)">
                @Html.DisplayFor(modelItem => item.DisciplineText)
            </td>
            <td data-id="@Html.DisplayFor(modelItem => item.Group)">
                @Html.DisplayFor(modelItem => item.GroupText)
            </td>
            <td data-id="@Html.DisplayFor(modelItem => item.Teacher)">
                @Html.DisplayFor(modelItem => item.TeacherText)
            </td>
            <td>
                @Html.ActionLink("Редактировать", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Подробно", "Details", new { id = item.Id }) |
                @Html.ActionLink("Удалить", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>