TimeTable/Controllers/GroupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TimeTable.DAO;
using TimeTable.Models;

namespace TimeTable.Controllers {
    public class GroupController : Controller {

        // GET: Group
        [Authorize(Roles = "Спец. по кадрам, Преподаватель")]
        public ActionResult Index() {
            return View(DAOGroup.GetGroups());
        }
    }
}

TimeTable/Controllers/LessonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TimeTable.DAO;
using TimeTable.Models;

namespace TimeTable.Controllers {
    public class LessonController : Controller {
        DAOLesson daoLesson = new DAOLesson();

        // GET: Lesson
        [Authorize(Roles = "Спец. по кадрам, Преподаватель")]
        public ActionResult Index() {
            return View(daoLesson.GetLessonContainer());
        }

        public ActionResult Disc() {
            return View(DAODiscipline.GetDisciplines());
        }

        public ActionResult Year() {
            return View(DAOGroup.GetGroups());
        }

        [Authorize(Roles = "Спец. по кадрам")]
        public ActionResult Create() {
            ViewBag.Message = daoLesson.GetLessonContainer();
            return View(new Lesson());
        }

        [HttpPost]
        public ActionResult Create([Bind(Exclude = "Id")] Lesson dl) {
            try {
                if (daoLesson.InsertLesson(dl))
                    return RedirectToAction("Index");
                else
                    return RedirectToAction("Index");
            } catch(Exception ex) {
                Logger.Logger.Log.Info("Не удалось создать заполнить клетку расписания: " + ex);
                return RedirectToAction("Index");
            }
        }

        [Authorize(Roles = "Спец. по кадрам, Преподаватель")]
        public ActionResult Details(int id) {
            return View(DAOLesson.GetLesson(id));
        }

        [Authorize(Roles = "Спец. по кадрам")]
        public ActionResult Delete(int id) {
            return View(DAOLesson.GetLesson(id));
        }

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection) {
            if (ModelState.IsValid && DAOLesson.DeleteLesson(id))
                return RedirectToAction("Index");
            return View();
        }

        // GET: Home/Edit/5
        [Authorize(Roles = "Спец. по кадрам")]
        public ActionResult Edit(int id) {
            ViewBag.Message = daoLesson.GetLessonContainer();
            return View(DAOLesson.GetLesson(id));
        }

        // POST: Home/Edit/5
        [HttpPost]
        public ActionResult Edit([Bind(Include = "Id, Discipline, Group, Teacher")]Lesson lesson) {
            if (ModelState.IsValid && DAOLesson.EditLesson(lesson))
                return RedirectToAction("Index");
            return View();
        }

    }
}

TimeTable/Controllers/ScheduleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TimeTable.DAO;
using TimeTable.Models;

namespace TimeTable.Controllers
{
    public class ScheduleController : Controller
    {
        // GET: Schedule
        [Authorize(Roles = "Спец. по кадрам, Преподаватель, Студент")]
        public ActionResult Index() {
            var group_id = Convert.ToInt32(Request.QueryString["group_id"] ?? "1");

            ViewBag.ActiveGroup = group_id;
            ViewBag.Group = DAOGroup.GetGroups();
            ViewBag.Pairs = DAOSchedule.GetPairs(group_id);

            return View(DAOSchedule.GetTimetable());
        }

    }
}

TimeTable/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TimeTable.DAO;

namespace TimeTable.Controllers {
    public class UserController : Controller {
        DAOUser daoUser = new DAOUser();

        // GET: User
        [Authorize(Roles = "Спец. по кадрам, Преподаватель")]
        public ActionResult Index() {
            return View(daoUser.GetUsers());
        }
    }
}

TimeTable/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <div class="dw-menu">
                    <ul>
                        <li>
                            @Html.ActionLink("Расписание", "Index", "Schedule", new { area = "" }, new { @class = "navbar-brand" })
                            <ul>
                                <li>
                                    @Html.ActionLink("Администрирование", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                                </li>
                            </ul>
                        </li>
                    </ul>

                    
                </div>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Занятия", "Index", "Lesson")</li>
                    <li>@Html.ActionLink("Дисциплины", "Index", "Discipline")</li>
                    <li>@Html.ActionLink("Группы", "Index", "Group")</li>
                    <li>@Html.ActionLink("Пользователи", "Index", "User")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Расписание ASP.NET Kuppuch</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    @Scripts.Render("~/bundles/modalWindow")
</body>
</html>